[package]
name = "address_book"
version = "0.1.0"
authors = ["Tjeerd Lafebre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"

[dependencies.rusqlite]
version = "0.22.0"
features = ["bundled"]